from math import *
# 'WS=4:LS=12:HS=3'cloudy-day store dimensions (ft)
# 'PRINT"1000'Cloudy store dimensions (ft):"WS;"x";LS;"x";hS
# 'AS=2*(WS+LS)*HS+2*WS*LS'cloudy store surface (ft^2)
# 'CS=WS*LS*HS*62.33'cloudy store capacitance (Btu/F)
Ds = 7.0
Hs = 4.0                                          # 'cloudy-day store dimensions (ft)
print("Cloudy store dimensions (ft):", Ds, "diam x", Hs, "high")
As = 2.0*pi*(Ds/2.0)**2.0+pi*Hs*Ds                # 'cloudy store surface (ft^2)
Rs = 36.0                                         # 'cloudy store R-value (ft^2-F-h/Btu)
Gs = As/Rs                                        # 'cloudy store thermal conductance (Btu/h-F)
Cs = pi*(Ds/2.0)**2.0*Hs*62.33                    # 'cloudy store capacitance (Btu/F)
Ts = 140.0                                        # 'average-day store temp (F)
Gh = 180.0                                        # 'total house conductance (Btu/h-F)
print("Total house conductance (Btu/h-F):", Gh)
Ta = 24.4                                         # 'average outdoor temp (F)
Th = 32.9                                         # 'average daily high (F)
Td = Ta-(Th-Ta)                                   # 'dawn temp (F)
Hd = (70.0-Td)*Gh                                 # 'dawn heat required at 70 F (Btu/h)
Grad = 1000.0                                     # 'radiator conductance (Btu/h-F)
Tm = 70.0+Hd/Grad                                 # 'min usable store temp (F)
print("Min/max cloudy store temp (F):", Tm, Ts)
Hs = (Ts-Tm)*Cs                                   # 'stored cloudy-day heat (Btu)
Hc = 24.0*(65.0-Ta)*Gh                            # 'heat required for 1 cloudy day (Btu/day)
Euse = 600.0                                      # 'indoor electrical use (kWh/mo)
He = 3412.0*Euse/30.0                             # 'electric heat (Btu/day)
Nd = Hs/(Hc-He)                                   # 'number of cloudy days stored
print("Number of cloudy days stored:", Nd)
print("Approximate solar fraction:", 1.0-2.0**(-Nd))
Es = 24.0*(Ts-65.0)*Gs                            # 'average day store loss (Btu/day)
Duse = 50.0                                       # 'DHW use (gal/day)
Ed = 8.33*Duse*(110.0-50.0)                       # 'DHW energy (Btu/day)
Estore = Es+Ed                                    # 'average store collection (Btu/day)
Ssun = 990.0                                      # 'sun on south wall (Btu/ft^2-day)
Swa = 96.0                                        # 'south window area (ft^2)
Swg = 0.5*Swa*Ssun                                # 'average south window gain (Btu/day)
Eday = Hc-Swg-He-Es                               # 'average sunspace air heating (Btu/day)
print("Estore, Eday (Btu/day):", Estore, Eday)
Dayl = 6.0                                        # 'solar collection day length (hours)
Nheat = (24.0-Dayl)*Eday/24.0                     # 'overnight heat (Btu/day)
Ndiff = 10.0                                      # 'day-night temp diff (F)
Chouse = Nheat/Ndiff                              # 'overnight house capacitance (Btu/F)
print("Overnight house capacitance (Btu/F):", Chouse)
Tday = (Ta+Th)/2.0                                # 'approximate daytime temp (F)
Tss = Tday+2.0*0.8*Ssun/Dayl                      # 'Thevenin sunspace temp (F)
Rss = Dayl/(Eday/(Tss-65.0)+Estore/(Tss-Ts))      # 'Thev SS resistance (F-h/Btu)
Tsc = Rss*Estore/(Tss-Ts)                         # 'store collection time (hours)
Tdc = Dayl-Tsc                                    # 'sunspace air heating time (hours)
print("Tstore, Tday (hours):", Tsc, Tdc)
Pp = 60.0                                         # 'pump power (watts)
Fp = 20.0                                         # 'fan power (watts)
Ce = Pp*Tsc+Fp*Dayl                               # 'collection energy (wH)
print("Collection energy (Wh):", Ce)
Cop = (Estore+Eday)/(3.412*Ce)                    # 'Coefficient Of Performance
print("Coefficient Of Performance (COP):", Cop)
Ag = 2.0/(Rss-1.0/Grad)                           # 'min sunspace glazing area (ft^2)
Hg = 8.0                                          # 'sunspace glazing height (ft)
Lg = Ag/Hg                                        # 'sunspace glazing length (ft)
Lgr = 4.0*int(Lg/4.0+1.0)                         # 'round up length to 4'
print("SS glazing dimensions (ft):", Hg, "high x", Lgr, "long")